### ISSUE TITLE
重启后模块有时不生效

### ISSUE THREAD

**Issue by 2064645009** [luckyzyx/LuckyTool#13]
因为我手机经常装模块，所以需要频繁重启，重启后模块有时不生效，但是再重启一次就生效了。
这个问题在Android12，ColorOS12.1也出现过，
现在我的系统版本是Android13，ColorOS13.0，机型是OPPO Reno5 5G。
希望修复。

**Comment by luckyzyx** [comment]
不是开发者的问题为什么让开发者妥协，再说了就一句话不生效，谁知道是什么原因

**Comment by 2064645009** [comment]
6
