### ISSUE TITLE
[功能请求] 去除快捷方式右下角图标

### ISSUE THREAD

**Issue by Master-Panda** [luckyzyx/LuckyTool#14]
**想要请求的功能**
作者你好，想要一个去除软件创建的快捷方式右下角原来的软件的图标的功能

**该功能的用途**
就是让图标更好看一点

**该功能实现的原理以及你对此功能的添加能做出什么帮助**
XXX

**Comment by luckyzyx** [comment]
已添加，ColorOS13+系统可用，等待版本更新
