### ISSUE TITLE
[Enhancement] Always show decimal percentage when charging

### ISSUE THREAD

**Issue by pesketo** [luckyzyx/LuckyTool#17]
Could you implement that when charging with SuperVOOC it always shows the decimal percentage and no notifications?

**Comment by luckyzyx** [comment]
This data is sent from inside the system and cannot be processed for the time being.

**Comment by ObiKeahloa** [comment]
> Could you implement that when charging with SuperVOOC it always shows the decimal percentage and no notifications?

Just to clarify
It's sent from the kernel. 
In a device tree file it specifies wether or not to  show decimals
