### ISSUE TITLE
[功能请求] 状态栏流量限速通知

### ISSUE THREAD

**Issue by CHENG23-nb** [luckyzyx/LuckyTool#2]
“流量使用已达限速额度，当前网络已被限速，详情请咨询运营商”
每次重启手机都弹出来，烦死了
![Screenshot_2022-09-03-10-27-03-74_b783bf344239542](https://user-images.githubusercontent.com/69061057/188253732-dcb38905-2138-46c4-a714-7551a64227b7.jpg)

**Comment by luckyzyx** [comment]
[点击前往TG](https://t.me/LuckyTool)
去频道绑定的讨论组里提取流量管理apk我再看看，我在C13找不到这个通知，或许和你的营业厅有关
