### ISSUE TITLE
[Feature Request] Lockscreen Time Format

### ISSUE THREAD

**Issue by oceangith** [luckyzyx/LuckyTool#22]
**想要请求的功能**
Customize the lockscreen Time format

**该功能的用途**
Customize Time format same as status bar Time format (add seconds, short weekday, etc.)

**该功能实现的原理以及你对此功能的添加能做出什么帮助**
XXX

**Comment by luckyzyx** [comment]
不同设备拥有不同的布局方式，无法进行统一处理
