### ISSUE TITLE
[Feature Request] Add space after comma in the functions list

### ISSUE THREAD

**Issue by Daviteusz** [luckyzyx/LuckyTool#23]
Could you add a toggle switch (e.g. in the app settings) that activates or deactivates the space after commas in the functions tab?
<img src="https://user-images.githubusercontent.com/11527277/228971433-a6d8ff3d-7a3b-4d0d-bf36-3959a320c664.jpg" width="20%" height="20%">

**Comment by luckyzyx** [comment]
I am not a translator of this language. You can go to Crowdin to check the corresponding translation.

**Comment by Daviteusz** [comment]
We didn't understand each other.
<img src="https://user-images.githubusercontent.com/11527277/229181444-47553266-d5fa-40b6-8673-27f5069d6f1f.png" width="60%">
In this case, the translator cannot add spaces, because the description is not a separate translation, but combined from two different translations. The comma is added by the code.

-----

<img src="https://user-images.githubusercontent.com/11527277/229183344-b9a54518-e608-4726-8f0e-e2d0c1cdfe28.png" width="30%">
Maybe a separate category description would be better instead of combining two different translations.
In this case, there is a separate translation for the category description
