### ISSUE TITLE
添加应用分身快捷入口

### ISSUE THREAD

**Issue by laomo** [luckyzyx/LuckyTool#24]
**想要请求的功能**
替换应用分身支持列表页，加一个直接跳转系统应用分身页面的入口，比如在右上角。

**该功能的用途**
快捷跳转到分身页面

**该功能实现的原理以及你对此功能的添加能做出什么帮助**
`am start com.oplus.multiapp/com.oplus.multiapp.ui.entry.ActivityMainActivity`

**Comment by luckyzyx** [comment]
已添加至v4.2.2_beta，敬请期待版本发布或前往TG讨论群下载
