### ISSUE TITLE
ColorOS11.1安卓11，更新最新版本后，启用模块，重启作用域或者手机，开机黑屏，电源键音量有反应，黑屏卡死似乎无触摸

### ISSUE THREAD

**Issue by LazilyCat** [luckyzyx/LuckyTool#25]
ColorOS11.1安卓11，更新最新版本后，启用模块，重启作用域或者手机，开机黑屏，电源键音量键有反应，但看不到画面，黑屏卡死似乎无触摸。

ColorOS11.1 Android 11, after updating the latest version, enable module, restart scope or phone, boot black screen, power button volume button response, but can not see the picture, black screen stuck seems no touch.

**Comment by luckyzyx** [comment]
ColorOS11的一切问题都不会被修复与适配，模块推荐系统ColorOS12+

**Comment by luckyzyx** [comment]
最新版本导致的系统界面崩溃，可以使用Magisk的安全模式禁用所有模块，具体教程前往酷安查询
