### ISSUE TITLE
Volume Slider right position 

### ISSUE THREAD

**Issue by M7MDE7EGAZY** [luckyzyx/LuckyTool#32]
![Screenshot_2023-09-11-07-52-55-65_a8e89bed8ceb754bee94ba00591e927a](https://github.com/luckyzyx/LuckyTool/assets/76889809/19106742-e7d7-40c8-8f7d-42a45b076f30)

Realme gt 2 pro based on cos 13.1

need slider adjustment**什么功能出现了问题**
XXX

**功能出现问题时你做了什么**
XXX

**模块的日志页面是否有报错**
XXX

**提供日志页面报错的截图**
XXX

**Comment by luckyzyx** [comment]
This shows that your system does not support it, and it has nothing to do with me.
