### ISSUE TITLE
[Feature Request] 去除日历部分页面信息流精彩推荐

### ISSUE THREAD

**Issue by BruceZhang1993** [luckyzyx/LuckyTool#37]
ColorOS 14.0.0.80
日历 package name:  com.coloros.calendar
version: 14.3.2

**想要请求的功能**
去除日历部分页面信息流精彩推荐

订阅节假日信息-选择日历日期-点击节假日入口-滑动到底部可见精彩推荐
Class name: com.android.calendar.module.subscription.horoscope.HoroscopeFragment.c

![图片](https://github.com/luckyzyx/LuckyTool/assets/6873988/7dde65ba-b0ea-45af-8e5f-8ad4fcfbe502)

**Comment by luckyzyx** [comment]
预计将在v1.1.4中正式发布
